### ISSUE TITLE
App Widget Cards Not Working

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre#37]
Mail and Calendar cards don't appear on the landing page. 

Drive and Classroom don't pull information.

Top 6 apps only pull the top 5 apps.

![2017-07-25_08-00-24](https://user-images.githubusercontent.com/16708913/28571122-5e90b4a2-710f-11e7-9005-a5188e420440.png)

**Comment by hcsdrose** [comment]
Updated refresh token fixed issue.
