### ISSUE TITLE
Directory Module: Add 4th Tab "Reports"

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre#46]
The directory module currently has 3 tabs for super admins:

1. Directory
2. Archived
3. Settings

I propose creating a 4 Tab called "Reports"

Move CSV exports (download all staff, download work calendars) to reports from settings.

Add a "License Expiring" Report that generates report both to end user and HR:

1. When licenses expire (sort by most recent expiration)
2. What license is expiring

Could get a little fuzzy with different states. Ohio has a unified expiration of June 30th.

(Not urgent, but tracking an HR request with this one).

**Comment by hcsdrose** [comment]
Closed with Latest Core Release
