### ISSUE TITLE
Stream is not displaying group type on reload

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre#57]
Minor.

When adding or editing a stream, the group type (staff, student, parents) is not displaying.

It is recording the group correctly in the database (verified).

![screen shot 2018-01-17 at 2 33 27 pm](https://user-images.githubusercontent.com/16708913/35062942-a0bd02a4-fb93-11e7-9686-7d16bcedf810.png)

**Comment by hcsdrose** [comment]
This is just an issue with "Students". Staff populates correctly.

**Comment by wilso199** [comment]
Already have the fix implemented. Will be in next release. I will update with a merge request number when I have it.

**Comment by zjvv** [comment]
As always, you guys are awesome.
