### ISSUE TITLE
Hover over icons in portal

### ISSUE THREAD

**Issue by stacys6808** [abreio/Abre#6]
Is it possible to hover over the icons in the portal to view the complete name of the app or site we are linking to?  The character limit is causing some confusion for a few of the apps. Thank you for your consideration!

**Comment by hcsdrose** [comment]
@zjvv Need some direction on how to address this using MD specs. Any suggestions?

**Comment by hcsdrose** [comment]
This has been fixed in 3.3.7. Rollover now allows for truncate removal and 2 lines of text in app drawer.
