### ISSUE TITLE
Streams/Comments Message empty message not showing

### ISSUE THREAD

**Issue by hcsdrose** [abreio/Abre#62]
When a user clicks Streams or Comments an empty message should show, however since the 4.2.9 update the message is not showing.

![image](https://user-images.githubusercontent.com/13473171/35223611-fa5a252a-ff4f-11e7-86f2-fbd089e93612.png)

**Comment by wilso199** [comment]
This will be resolved with #64.

**Comment by hcsdrose** [comment]
Fixed with 4.3.0
