### ISSUE TITLE
App drawer not separating out student/staff apps

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre#63]
Students are seeing all apps when clicking on App drawer. This is problematic as the gradebook apps is redirecting them to the teacher login screen (and they're getting rejected).

On a good note, the App widget is showing correctly!

![screen shot 2018-01-22 at 8 42 08 am](https://user-images.githubusercontent.com/16708913/35223748-8e113f92-ff50-11e7-8353-ec2d514e3831.png)

**Comment by hcsdrose** [comment]
Fixed with 4.3.0
